import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { hrApi } from "@/api/hr";
import type { Employee } from "@/types/hr";
import { useUserRoles, hasAnyRole } from "@/lib/rbac";
import { Button } from "@/components/ui/button";
import { EmployeeFormDialog } from "@/components/hr/EmployeeFormDialog";
import { TerminateDialog } from "@/components/hr/TerminateDialog";
export default function EmployeesPage(){
 const roles=useUserRoles();const canEdit=hasAnyRole(roles,["super_admin","hr"]);const[items,setItems]=useState<Employee[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[status,setStatus]=useState("");const[search,setSearch]=useState("");const[form,setForm]=useState(false);const[editing,setEditing]=useState<Employee|null>(null);const[terminate,setTerminate]=useState<Employee|null>(null);
 async function load(){setLoading(true);try{setItems(await hrApi.employees(status?{status:status as Employee["status"]}:undefined));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load employees")}finally{setLoading(false)}}useEffect(()=>{void load()},[status]);
 const filtered=useMemo(()=>items.filter(e=>{const n=`${e.user?.first_name??""} ${e.user?.last_name??""} ${e.user?.email??""} ${e.job_title} ${e.department??""}`.toLowerCase();return n.includes(search.toLowerCase())}),[items,search]);
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Employees</h1><p className="text-sm text-muted-foreground">Employee records, contracts and compensation.</p></div>{canEdit&&<Button onClick={()=>{setEditing(null);setForm(true)}}>Add employee</Button>}</div><div className="flex flex-wrap gap-3"><input className="rounded-md border bg-background p-2" placeholder="Search employees..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded-md border bg-background p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="on_leave">On leave</option><option value="suspended">Suspended</option><option value="terminated">Terminated</option></select></div>{error&&<div className="rounded border border-destructive/30 p-4 text-destructive">{error}<Button className="ml-3" size="sm" variant="outline" onClick={()=>void load()}>Retry</Button></div>}{loading?<p>Loading...</p>:<div className="overflow-x-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted"><tr>{["Employee","Type","Department","Contract","Compensation","Status",""].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{filtered.map(e=><tr key={e.id} className="border-t"><td className="p-3"><Link className="font-medium text-primary hover:underline" to={`/hr/employees/${e.id}`}>{e.user?`${e.user.first_name} ${e.user.last_name}`:e.employee_number||e.id.slice(0,8)}</Link><div className="text-xs text-muted-foreground">{e.user?.email}</div></td><td className="p-3">{e.employee_type}</td><td className="p-3">{e.department||"â€”"}<div className="text-xs text-muted-foreground">{e.job_title}</div></td><td className="p-3">{e.contract_start?.slice(0,10)}{e.contract_end?` â†’ ${e.contract_end.slice(0,10)}`:""}</td><td className="p-3">{e.salary?`${e.salary} ${e.currency||"EGP"}`:e.hourly_rate?`${e.hourly_rate} EGP/hr`:"â€”"}</td><td className="p-3">{e.status}</td><td className="p-3 text-right">{canEdit&&<div className="flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={()=>{setEditing(e);setForm(true)}}>Edit</Button>{e.status!=="terminated"&&<Button size="sm" variant="ghost" onClick={()=>setTerminate(e)}>Terminate</Button>}</div>}</td></tr>)}</tbody></table>{filtered.length===0&&<p className="p-8 text-center text-muted-foreground">No employees found.</p>}</div>}<EmployeeFormDialog open={form} employee={editing} onClose={()=>setForm(false)} onSaved={()=>void load()}/><TerminateDialog open={!!terminate} employeeId={terminate?.id} onClose={()=>setTerminate(null)} onSaved={()=>void load()}/></div>
}

