import { useEffect,useState } from "react";
import { Link,useParams } from "react-router-dom";
import { hrApi } from "@/api/hr";
import { filesApi } from "@/api/files";
import type { Employee, EmployeeDocument, DocumentType } from "@/types/hr";
import { Button } from "@/components/ui/button";
import { EmployeeFormDialog } from "@/components/hr/EmployeeFormDialog";
import { AvailabilityPanel } from "@/components/hr/AvailabilityPanel";
export default function EmployeeDetailsPage(){
 const{id}=useParams();const[employee,setEmployee]=useState<Employee|null>(null);const[docs,setDocs]=useState<EmployeeDocument[]>([]);const[form,setForm]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[name,setName]=useState("");const[type,setType]=useState<DocumentType>("contract");const[expiry,setExpiry]=useState("");const[file,setFile]=useState<File|null>(null);
 async function load(){if(!id)return;try{const[e,d]=await Promise.all([hrApi.employee(id),hrApi.documents(id)]);setEmployee(e);setDocs(d)}catch(e){setError(e instanceof Error?e.message:"Unable to load employee")}}
 useEffect(()=>{void load()},[id]);
 async function upload(){if(!id||!file||!name){setError("Document name and file are required");return;}setBusy(true);try{const f=await filesApi.upload(file,"hr");await hrApi.addDocument({employee_id:id,name,file_url:f.file_url,document_type:type,expiry_date:expiry||undefined});setFile(null);setName("");setExpiry("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to upload document")}finally{setBusy(false)}}
 async function remove(docId:string){if(!window.confirm("Delete this document?"))return;try{await hrApi.deleteDocument(docId);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete document")}}
 if(!employee)return <div><Link className="text-primary" to="/hr">← Employees</Link><p className="mt-4">{error||"Loading..."}</p></div>;
 const fullName=employee.user?`${employee.user.first_name} ${employee.user.last_name}`:employee.employee_number||employee.id;
 return <div className="space-y-6"><div><Link className="text-sm text-primary" to="/hr">← Employees</Link><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{fullName}</h1><p className="text-muted-foreground">{employee.job_title} · {employee.department||"No department"}</p></div><Button onClick={()=>setForm(true)}>Edit employee</Button></div></div>{error&&<p className="text-destructive">{error}</p>}<section className="grid gap-4 rounded-lg border p-5 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Employment</p><p>{employee.employee_type} · {employee.status}</p></div><div><p className="text-xs text-muted-foreground">Contract</p><p>{employee.contract_start?.slice(0,10)}{employee.contract_end?` → ${employee.contract_end.slice(0,10)}`:""}</p></div><div><p className="text-xs text-muted-foreground">Compensation</p><p>{employee.salary?`${employee.salary} ${employee.currency||"EGP"} fixed`:employee.hourly_rate?`${employee.hourly_rate} EGP/hour`:"Not set"}</p></div></section><section className="rounded-lg border p-5"><h2 className="mb-4 text-lg font-semibold">Documents</h2><div className="grid gap-3 md:grid-cols-5"><input className="rounded border bg-background p-2 md:col-span-2" placeholder="Document name" value={name} onChange={e=>setName(e.target.value)}/><select className="rounded border bg-background p-2" value={type} onChange={e=>setType(e.target.value as DocumentType)}>{["contract","id","certificate","visa","other"].map(x=><option key={x}>{x}</option>)}</select><input type="date" className="rounded border bg-background p-2" value={expiry} onChange={e=>setExpiry(e.target.value)}/><input type="file" className="rounded border p-2" onChange={e=>setFile(e.target.files?.[0]??null)}/></div><div className="mt-3"><Button disabled={busy} onClick={()=>void upload()}>{busy?"Uploading...":"Upload document"}</Button></div><div className="mt-5 divide-y rounded border">{docs.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><a className="text-primary hover:underline" href={d.file_url} target="_blank" rel="noreferrer">{d.name}</a><p className="text-xs text-muted-foreground">{d.document_type}{d.expiry_date?` · expires ${d.expiry_date.slice(0,10)}`:""}</p></div><Button size="sm" variant="ghost" onClick={()=>void remove(d.id)}>Delete</Button></div>)}{docs.length===0&&<p className="p-5 text-sm text-muted-foreground">No documents.</p>}</div></section><section className="rounded-lg border p-5"><h2 className="mb-4 text-lg font-semibold">Teacher availability</h2><AvailabilityPanel employeeId={employee.id}/></section><EmployeeFormDialog open={form} employee={employee} onClose={()=>setForm(false)} onSaved={()=>void load()}/></div>
}
