import { useState } from "react";
import { hrApi } from "@/api/hr";
import type { LeaveType } from "@/types/hr";
import { Button } from "@/components/ui/button";
export function LeaveRequestDialog({open,employeeId,onClose,onSaved}:{open:boolean;employeeId?:string;onClose:()=>void;onSaved:()=>void}){
 const [type,setType]=useState<LeaveType>("annual");const[start,setStart]=useState("");const[end,setEnd]=useState("");const[reason,setReason]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 if(!open||!employeeId)return null;
 function days(){if(!start||!end)return 0;const a=new Date(start+"T00:00:00").getTime(),b=new Date(end+"T00:00:00").getTime();return Math.floor((b-a)/86400000)+1}
 async function submit(){const d=days();if(d<1){setError("End date must be on or after start date");return;}setBusy(true);try{await hrApi.requestLeave({employee_id:employeeId!,type,start_date:start,end_date:end,days_count:d,reason:reason||undefined});onSaved();onClose();}catch(e){setError(e instanceof Error?e.message:"Unable to submit leave");}finally{setBusy(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-lg border bg-background p-6"><h2 className="text-lg font-semibold">Request leave</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Type<select className="mt-1 w-full rounded border bg-background p-2" value={type} onChange={e=>setType(e.target.value as LeaveType)}>{["annual","sick","emergency","unpaid","other"].map(x=><option key={x}>{x}</option>)}</select></label><div/><label className="text-sm">Start<input type="date" className="mt-1 w-full rounded border bg-background p-2" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm">End<input type="date" className="mt-1 w-full rounded border bg-background p-2" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><textarea className="mt-3 min-h-24 w-full rounded border bg-background p-2" placeholder="Reason" value={reason} onChange={e=>setReason(e.target.value)}/>{error&&<p className="mt-2 text-sm text-destructive">{error}</p>}<div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy} onClick={submit}>{busy?"Submitting...":"Submit request"}</Button></div></div></div>
}

